//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resoures {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResourceFiles.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رکوردی برای حذف انتخاب نشده است.
        /// </summary>
        public static string DeleteMsgNoRecord {
            get {
                return ResourceManager.GetString("DeleteMsgNoRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا مطمئن هستید ردیف {0} حذف شود؟.
        /// </summary>
        public static string DeleteMsgWithItemNo {
            get {
                return ResourceManager.GetString("DeleteMsgWithItemNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا مطمئن هستید ردیف جاری حذف شود؟.
        /// </summary>
        public static string DeleteMsgWithoutItemNo {
            get {
                return ResourceManager.GetString("DeleteMsgWithoutItemNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان را وارد کنید.
        /// </summary>
        public static string EnterTitleMsg {
            get {
                return ResourceManager.GetString("EnterTitleMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آبجکت مورد نظر پیدا نشد.
        /// </summary>
        public static string FailedFindMsg {
            get {
                return ResourceManager.GetString("FailedFindMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در دریافت اطلاعات.
        /// </summary>
        public static string FailedGetMsg {
            get {
                return ResourceManager.GetString("FailedGetMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رکوردی برای نمایش وجود ندارد.
        /// </summary>
        public static string NoRecords {
            get {
                return ResourceManager.GetString("NoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to را وارد کنید {0} لطفا.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف با موفقیت انجام شد.
        /// </summary>
        public static string SuccessDeleteMsg {
            get {
                return ResourceManager.GetString("SuccessDeleteMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن رکورد جدید با موفقیت انجام شد.
        /// </summary>
        public static string SuccessInsertMsg {
            get {
                return ResourceManager.GetString("SuccessInsertMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت با موفقیت انجام شد.
        /// </summary>
        public static string SuccessSaveMsg {
            get {
                return ResourceManager.GetString("SuccessSaveMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به روز رسانی با موفقیت انجام شد.
        /// </summary>
        public static string SuccessUpdateMsg {
            get {
                return ResourceManager.GetString("SuccessUpdateMsg", resourceCulture);
            }
        }
    }
}
